"""add coupon management tables

Revision ID: d5a8b3a2c9d1
Revises: fb120f8fc198
Create Date: 2025-11-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = 'd5a8b3a2c9d1'
down_revision = 'fb120f8fc198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_user_id', UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_coupons_brand'), 'coupons', ['brand'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_index(op.f('ix_coupons_tag'), 'coupons', ['tag'], unique=False)
    
    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', UUID(as_uuid=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_coupons_id'), 'user_coupons', ['id'], unique=False)
    
    # Add role_id column to user table
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('display_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'display_name')
    op.drop_column('user', 'role_id')
    op.drop_index(op.f('ix_user_coupons_id'), table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index(op.f('ix_coupons_tag'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_brand'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###